//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAMusicPlayer2
{
    using System;
    using System.Collections.Generic;
    
    public partial class AAList
    {
        public int Id { get; set; }
        public string artist { get; set; }
        public string title { get; set; }
        public string genre { get; set; }
        public string filename { get; set; }
        public string path { get; set; }
        public Nullable<int> length { get; set; }
        public Nullable<System.DateTime> dateAdded { get; set; }
        public string album { get; set; }
        public Nullable<int> order { get; set; }
    }
}
